"""Start Caddy as an HTTPS reverse proxy in front of the CMMS app.

    python deploy/start_caddy.py      (or double-click "Start HTTPS (Caddy).bat")

Why: phones only allow "install as app" + push notifications over HTTPS.
This detects the PC's LAN IP, writes deploy/Caddyfile.local pointing HTTPS
at the app on port 8000, and launches Caddy with a locally-trusted cert.
Each phone trusts Caddy's root CA once — see deploy/HTTPS-SETUP.md.
"""
import os, shutil, socket, subprocess, sys

PORT = os.environ.get("PORT", "8000")
HERE = os.path.dirname(os.path.abspath(__file__))


def lan_ip():
    """Best-guess LAN IPv4 of this PC (same trick run.py uses)."""
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        s.connect(("8.8.8.8", 80))
        return s.getsockname()[0]
    except Exception:
        return "127.0.0.1"
    finally:
        s.close()


def find_caddy():
    exe = shutil.which("caddy")
    if exe:
        return exe
    local = os.path.join(HERE, "..", "caddy.exe")
    return local if os.path.exists(local) else None


def main():
    caddy = find_caddy()
    if not caddy:
        sys.exit("caddy not found. Install it first — see deploy/HTTPS-SETUP.md\n"
                 "  (scoop install caddy  /  choco install caddy  /  put caddy.exe in the project root)")
    ip = lan_ip()
    cfg = os.path.join(HERE, "Caddyfile.local")
    with open(cfg, "w", encoding="utf-8") as f:
        f.write(
            "# AUTO-GENERATED by start_caddy.py — regenerated every run, do not edit.\n"
            "{\n"
            "\tauto_https disable_redirects\n"   # don't bind port 80 (often blocked/reserved on Windows)
            "}\n"
            "bflfp.local {\n"
            "\ttls internal\n"
            f"\treverse_proxy localhost:{PORT}\n"
            "}\n"
            f"https://{ip} {{\n"
            "\ttls internal\n"
            f"\treverse_proxy localhost:{PORT}\n"
            "}\n"
        )
    print("\n  BFLFP CMMS — HTTPS proxy for phones")
    print(f"   Phones open : https://{ip}")
    print("   (or https://bflfp.local if your wifi supports mDNS)")
    print("   First time on each phone: trust the Caddy CA — see deploy/HTTPS-SETUP.md\n")
    subprocess.run([caddy, "run", "--config", cfg])


if __name__ == "__main__":
    main()
